// Generates `scripts/seed.sql` with 100 fake users for local testing.
//
// Run via `npm run db:seed:local`, which chains this generator with
// `wrangler d1 execute`. The output file is gitignored — regenerate it any time.
//
// Emails embed the row index, so every generated email is unique even when the
// first/last name combination repeats.

import {writeFileSync} from 'node:fs';
import {dirname, join} from 'node:path';
import {fileURLToPath} from 'node:url';

const FIRST_NAMES = [
  'Ada', 'Alan', 'Grace', 'Linus', 'Margaret', 'Dennis', 'Barbara', 'Ken',
  'Radia', 'Guido', 'Katherine', 'Bjarne', 'Hedy', 'James', 'Anita', 'Donald',
  'Frances', 'Tim', 'Shafi', 'Vint', 'Jean', 'Larry', 'Sophie', 'Anders',
  'Carol',
];

const LAST_NAMES = [
  'Lovelace', 'Turing', 'Hopper', 'Torvalds', 'Hamilton', 'Ritchie', 'Liskov',
  'Thompson', 'Perlman', 'Rossum', 'Johnson', 'Stroustrup', 'Lamarr', 'Gosling',
  'Borg', 'Knuth', 'Allen', 'Berners-Lee', 'Goldwasser', 'Cerf', 'Bartik',
  'Wall', 'Wilson', 'Hejlsberg', 'Shaw',
];

const DOMAINS = ['example.com', 'example.org', 'example.net', 'test.dev'];

const COUNT = 100;

const rows = [];
for (let i = 0; i < COUNT; i++) {
  const first = FIRST_NAMES[i % FIRST_NAMES.length];
  const last = LAST_NAMES[(i * 7) % LAST_NAMES.length];
  const name = `${first} ${last}`;
  const email = `${first}.${last}${i}@${DOMAINS[i % DOMAINS.length]}`.toLowerCase();
  rows.push(`  ('${name}', '${email}')`);
}

const sql = [
  '-- Auto-generated by scripts/generate-seed.mjs. Do not edit by hand.',
  '-- Seeds 100 fake users into the users_table for local testing.',
  'INSERT INTO users_table (name, email) VALUES',
  rows.join(',\n') + ';',
  '',
].join('\n');

const outPath = join(dirname(fileURLToPath(import.meta.url)), 'seed.sql');
writeFileSync(outPath, sql);
console.log(`Wrote ${COUNT} users to ${outPath}`);
